### ISSUE TITLE
Cannot upload files from Safari, Chrome

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#116]
When attempting to upload a main file to drafts, I can open the uploadcare modal and select a file, but when I confirm the file the modal closes and nothing happens.

https://user-images.githubusercontent.com/28573875/144205227-b092b178-1b32-4f82-8f2a-15168fb1a182.mov

**Comment by chartgerink** [comment]
Which browser is this happening in for you? 

I cannot reproduce in Firefox, but was able to reproduce in Safari and Chrome.

**Comment by psobrakseaton** [comment]
> Which browser is this happening in for you?
> 
> I cannot reproduce in Firefox, but was able to reproduce in Safari and Chrome.

Good question, I was using Safari when this error happened to me.

**Comment by chartgerink** [comment]
Debugging a bit right now and it seems like this is in part the result of the secure uploading.

The page asks the server for the security signature to upload the file with, but then when it is being uploaded it asks for it again, which updates the signature and then makes the widget close as a result.

I will disable the secure uploading for now and open up a new issue to make sure to re-enable it. This is primarily because it is taking me more time than I have for the bughunt tomorrow 😅
