### ISSUE TITLE
If I start to change my information in settings and switch the settings tab, my form information is reset...

### ISSUE THREAD

**Issue by psobrakseaton** [libscie/ResearchEquals.com#235]
I was changing some information in my bio, and when I swapped from the "Workspace" tab of the settings modal to the "Account" tab and swapped back, the changes were reset and I lost my previously written (yet unsaved) bio information.

Perhaps there should be a prompt to save your work should you have changed anything in the form and attempt to close/change tabs.

**Comment by noahsprent** [comment]
Also noticed this today when clicking to add Orcid during profile setup

**Comment by chartgerink** [comment]
This seems to also be an issue in the draft window, where the edited metadata gets reset when the form is open, but (for example) a reference is added.

This indicates it seems to be a general issue about state management for forms rather than a bug specific to the settings window. I'll investigate to find a better way to manage state (maybe [RecoilJS](https://recoiljs.org/)).
