### ISSUE TITLE
Deleting an account fails when a token exists for a password reset

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#372]
Deleting an account fails when there is an existing token for resetting a password.

## Steps to reproduce
1. Create an account
2. Log out 
3. Do "forgot password" 
4. Log in to the account (without actually resetting a password)
5. Delete account --> 500 error 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/17035406/165177394-06a09932-65e1-4ba5-8be9-486524140f3f.png">

```
Error: Foreign key constraint failed on the field: `Token_userId_fkey (index)`
```

```
Uncaught (in promise) Error: Foreign key constraint failed on the field: `Token_userId_fkey (index)`
```

I think the solution is to set up a cascading delete for the Prisma schema. (e.g., https://github.com/nsunami/postreview-app/commit/c82d12222fb65dbb4c8f967bb51df7bb09e4695c)

Maybe a small bug, but it may be a good practice to cascade-delete the existing tokens.

**Comment by chartgerink** [comment]
Thanks @nsunami! May I ask how you found out? I'm intrigued whether this was a part of a testing area or local dev?

In any case, I think cascading is a good idea. I didn't implement before because I was afraid it would cascade beyond and delete workspaces, published modules. Do you happen to know whether we can limit the cascade to for example the tokens? 

The outcome should be that the user gets deleted, and associated sessions, tokens, drafts for single membership workspaces, and workspaces that have no published modules linked to them (I think that's the complete list).

**Comment by nsunami** [comment]
I was working on PostReview and found out about this bug. Since the code was part of the Blitz.js template, I tested the same process on R=. (Probably the template should have `onDelete: Cascade` to begin with?)

And yes! We can limit cascading to specific relations, and leave out others. (e.g., PostReview leaves out articles, and fills the submitter ID to `null`). So, we can leave out the published modules when the user leaves the platform. 👍
